// Stage-specific configuration for detail views

export interface StageTimelineStep {
  text: string;
  done?: boolean;
  current?: boolean;
}

export interface StageUploadSlot {
  id: string;
  name: string;
  desc: string;
  required: boolean;
  critical: boolean;
}

export interface StageDocConfig {
  id: string;
  name: string;
  matchName: string; // partial name match against documents table
  locked: boolean;
  lockedMessage: string;
}

export interface StageConfig {
  timeline: StageTimelineStep[];
  uploads: StageUploadSlot[];
  docs: StageDocConfig[];
  nextInfo: string | null;
  wgFeatures: string[];
}

export const STAGE_CONFIG: Record<number, StageConfig> = {
  1: {
    timeline: [
      { text: "Intake completed" },
      { text: "Request letter generated by AI" },
      { text: "LOMN template generated" },
      { text: "Review & finalize request letter" },
      { text: "Upload signed LOMN from doctor" },
      { text: "Submit request package to MLTC" },
      { text: "Await MLTC determination (2–4 weeks)" },
    ],
    uploads: [
      {
        id: "u1",
        name: "Letter of Medical Necessity (LOMN)",
        desc: "Signed letter from your doctor supporting the request",
        required: true,
        critical: true,
      },
      {
        id: "u2",
        name: "Recent Medical Records",
        desc: "Hospital visits, test results, or doctor's notes",
        required: false,
        critical: false,
      },
      {
        id: "u3",
        name: "Other Supporting Documents",
        desc: "Any additional documents",
        required: false,
        critical: false,
      },
    ],
    docs: [
      {
        id: "sg1_ripc",
        name: "Request for Increase in Plan of Care",
        matchName: "Request for Increase",
        locked: false,
        lockedMessage: "",
      },
      {
        id: "sg1_lomn",
        name: "LOMN Request Template (for your Doctor)",
        matchName: "LOMN",
        locked: false,
        lockedMessage: "",
      },
    ],
    nextInfo:
      "If the MLTC denies or partially denies your request, they will issue an Initial Adverse Determination (IAD). You can then proceed to Stage 2: Internal Appeal.",
    wgFeatures: [
      "We submit the request package to your MLTC",
      "Direct communication with your case manager",
      "Follow-up calls and deadline tracking",
      "Dedicated advocate assigned to your case",
    ],
  },
  2: {
    timeline: [
      { text: "Upload IAD from MLTC" },
      { text: "AI analyzes IAD and generates appeal" },
      { text: "Review & finalize appeal letter" },
      { text: "Submit Internal Appeal to MLTC" },
      { text: "Await appeal decision (30–60 days)" },
    ],
    uploads: [
      {
        id: "u4",
        name: "Initial Adverse Determination (IAD)",
        desc: "The denial letter from your MLTC — required to generate your appeal",
        required: true,
        critical: true,
      },
      {
        id: "u5",
        name: "Updated LOMN (if available)",
        desc: "A more recent letter from your doctor",
        required: false,
        critical: false,
      },
      {
        id: "u6",
        name: "Additional Medical Evidence",
        desc: "New test results, hospital records, or specialist reports",
        required: false,
        critical: false,
      },
    ],
    docs: [
      {
        id: "sg2_appeal",
        name: "Internal Appeal Letter",
        matchName: "Internal Appeal",
        locked: true,
        lockedMessage:
          "This letter will be generated after you upload the IAD from your MLTC. The AI will analyze their determination and craft a targeted appeal.",
      },
    ],
    nextInfo:
      "If the MLTC denies your Internal Appeal, they will issue a Final Adverse Determination (FAD). You can then proceed to Stage 3: Fair Hearing.",
    wgFeatures: [
      "We submit the Internal Appeal on your behalf",
      "Follow up with the MLTC appeals department",
      "Track deadlines and ensure timely processing",
      "Dedicated advocate manages all communications",
    ],
  },
  3: {
    timeline: [
      { text: "Upload FAD from MLTC" },
      { text: "Request Fair Hearing with NYS OTDA" },
      { text: "Receive MLTC evidence package (includes UAS)" },
      { text: "AI analyzes UAS and generates Memo of Law" },
      { text: "Review & finalize Memo of Law" },
      { text: "Attend Fair Hearing (2–3 months)" },
      { text: "Receive judge's decision" },
    ],
    uploads: [
      {
        id: "u7",
        name: "Final Adverse Determination (FAD)",
        desc: "The final denial from your MLTC",
        required: true,
        critical: true,
      },
      {
        id: "u8",
        name: "UAS Report / MLTC Evidence Package",
        desc: "The evidence package including the UAS assessment",
        required: true,
        critical: true,
      },
      {
        id: "u9",
        name: "Updated LOMN",
        desc: "Most recent letter from your doctor",
        required: false,
        critical: false,
      },
      {
        id: "u10",
        name: "Other Evidence",
        desc: "Photos, personal statements, caregiver logs",
        required: false,
        critical: false,
      },
    ],
    docs: [
      {
        id: "sg3_hearing",
        name: "Fair Hearing Request",
        matchName: "Fair Hearing",
        locked: true,
        lockedMessage:
          "This request will be generated after you upload the FAD.",
      },
      {
        id: "sg3_memo",
        name: "Memo of Law",
        matchName: "Memo of Law",
        locked: true,
        lockedMessage:
          "This legal memorandum will be generated after we receive and analyze the MLTC's evidence package, including the UAS report.",
      },
    ],
    nextInfo: null,
    wgFeatures: [
      "We file the Fair Hearing request with NYS OTDA",
      "Full analysis of UAS report and evidence package",
      "Hearing preparation and evidence organization",
      "Dedicated advocate attends the hearing with you",
    ],
  },
};
